version: '2'
services:
  oauth2:
    build: .
    ports:
    - "8888:8080"
    networks:
      - network
  idapi:
    image: rlkamradt/useridservice
    ports:
      - "3000:3000"
    networks:
      - network
  intidapi:
    image: rlkamradt/useridservice
    environment:
      - NO_AUTH=true
    ports:
      - "3001:3000"
    networks:
      - network
  redis:
    image: redis:alpine
    networks:
      - network
networks:
  network:
